typography_spectrum: 0.3673835
color:
  brandColors:
    - '#dbd8d3'
    - '#928f8a'
    - '#8b2926'
    - '#410c00'
    - '#e67c6f'
  brandStrength: 0.0625
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: niteip
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Nothing is true, everything is permitted'
purpose: []
