title: 'Nothing is true, everything is permitted'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7847233768552542
  brandStrength: 0.5
  rhythmicContrast: 0.6300194833893329
  brandColors:
    - '#dbd8d3'
    - '#928f8a'
    - '#8b2926'
    - '#410c00'
    - '#e67c6f'
  lightness: 0.6875
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: niteip
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.85853
layout_spectrum: 0.6487455
