title: 'Nothing is true, everything is permitted'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.3566308
  brandStrength: 0.202509
  lightness: 0.2526882
  brandColors:
    - '#dbd8d3'
    - '#928f8a'
    - '#8b2926'
    - '#410c00'
    - '#e67c6f'
  rhythmicContrast: 0.6300195
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: niteip
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.85853
layout_spectrum: 0.7437276
