title: 'Nothing is true, everything is permitted'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.2968361
  brandStrength: 0.7293907
  lightness: 0.6623017
  brandColors:
    - '#DBD8D3'
    - '#928F8A'
    - '#8B2926'
    - '#3A3633'
    - '#825850'
  rhythmicContrast: 0.2921147
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: niteip
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8108001002110541
layout_spectrum: 0.9659498
